### PR TITLE
Adding service management for the webserver

### PR DESCRIPTION
**Pull request by jschaeff**
This is a simple addition to manage dsm_om_connsvc service if omsa::install_webserver is enabled.

### CODE REVIEW

**Comment by vide** [comment]
Thanks a lot! I'm not a webserver user myself so I didn't investigate too much that this was needed

**Comment by jschaeff** [comment]
Thanks to you for this awesome module. Could you also update the version ?

**Comment by vide** [comment]
Well, I was waiting to add some more features (basically SNMP integration) to release 0.2

**Comment by jschaeff** [comment]
right :)

**Pull request merged**
